### ISSUE TITLE
Error keeps popping up on Kodi 17 - Windows

### ISSUE THREAD

**Issue by danazkari** [markop159/KODI-Popcorn-Time#64] opened 2017-02-08 16:02 UTC
Hi,

I have a windows 10 machine that I use exclusively for gaming and HTPC purposes, I love popcorn-time and Kodi, but for some reason I keep getting an error whenever I try to get in to the add-on menu.

Kodi's log doesn't have the log, and the error message doesn't say much, just to look at the log which... well.. is empty.

So after reading about the project a little bit, I'm starting to wonder.... Does this add-on have support for windows? If so, let me know if you need more info on the issue and I could dive a little bit deeper.

**Comment by markop159** [comment] 2017-02-08 19:23
I would need a little bit more info. I am using this addon on both Windows 10 and Raspberry Pi, on both is installed Kodi 17.
Are you using Kodi from windows store or classic aplication?
I would still need some logs to debug error.

**Comment by Darkein** [comment] 2017-02-08 20:32
Hello,
i have the same problem since i have updated osmc, but my log are more verbose :)
`21:21:50.219 T:1494193136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named simplejson
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 6, in <module>
                                                from kodipopcorntime import gui
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/__init__.py", line 1, in <module>
                                                ﻿from .browse import Browse as browse
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/browse.py", line 3, in <module>
                                                from .base3 import _Base3
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/base3.py", line 3, in <module>
                                                from .base2 import _Base2
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/base2.py", line 6, in <module>
                                                from kodipopcorntime.utils import xbmcItem, cleanDebris
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/utils.py", line 2, in <module>
                                                import xbmcgui, xbmc, simplejson, sys, time, os, UserDict, socket, glob
                                            ImportError: No module named simplejson
                                            -->End of Python script error report<--
21:21:50.447 T:1958572976   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/
21:21:50.448 T:1958572976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/) failed
21:24:05.115 T:1718088688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named simplejson
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 6, in <module>
                                                from kodipopcorntime import gui
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/__init__.py", line 1, in <module>
                                                ﻿from .browse import Browse as browse
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/browse.py", line 3, in <module>
                                                from .base3 import _Base3
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/base3.py", line 3, in <module>
                                                from .base2 import _Base2
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/base2.py", line 6, in <module>
                                                from kodipopcorntime.utils import xbmcItem, cleanDebris
                                              File "/home/osmc/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/utils.py", line 2, in <module>
                                                import xbmcgui, xbmc, simplejson, sys, time, os, UserDict, socket, glob
                                            ImportError: No module named simplejson
                                            -->End of Python script error report<--
21:24:05.365 T:1958572976   ERROR: GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/
21:24:05.366 T:1958572976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/) failed`

**Comment by Darkein** [comment] 2017-02-08 20:36
just tried to come back to the 1.6.7 version, and it works!

**Comment by markop159** [comment] 2017-02-09 04:47
Tnx for log. Will revert some changes and update. Untill then please try to use version 1.6.7 and disable auto update.

**Comment by markop159** [comment] 2017-02-13 07:54
@danazkari @Darkein now it should be safe to update to version 1.6.9. If it is working please close this Issue.

**Comment by gabrielgradinaru** [comment] 2017-02-15 20:12
@danazkari @Darkein are you able to get the kodi logs for version 1.6.8 ? (http://kodi.wiki/view/Log_file/Easy)

**Comment by Darkein** [comment] 2017-02-16 08:59
@gabrielgradinaru yes, that's what i've done.
@markop159 i'm sorry i cant test it for 2 weeks. I will keep you in touch asap

**Comment by gabrielgradinaru** [comment] 2017-02-16 20:02
@Darkein The error you were receiving was because the simplejson module was not available for some reason in your kodi installation and we have to figure out why.
So can you provide the full kodi log? Because just the error portion is not enough to reach a conclusion.

**Comment by Darkein** [comment] 2017-02-16 20:53
Ah OK, that's maybe because i'm using osmc. I can't access to the logs for
now, i will send them to you asap.

**Comment by markop159** [comment] 2017-02-16 21:04
I am using OSMC and on my instalation this was working ok (I would not update if it was not working). Maybe because I have some additional repos installed. But I cannot reproducirati this error on default instalation on Windows 10.

**Closed** 2017-03-15 00:19 UTC
